[package]
name = "collections"
version = "0.1.0"
authors = ["Malachi Austin <malachiaustin02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown   = "0.7.0"
